version: "3"
services:
  api:
    build:     
      context: .   
      dockerfile: Dockerfile
    environment:   
      - MONGO_URL=mongodb://db:27017/cinema
    depends_on:
      - db
    volumes: 
     - .:/app  
    ports:
      - 3000:3000  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api"]
      interval: 1m30s
      timeout: 10s
      retries: 3  

  db:  
    image: mongo:latest
    ports:
      - 27017:27017   